security:
    encoders:
        Pladuch\BackBundle\Entity\Usuario:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    providers:
        sga:
            entity: { class: 'PladuchBackBundle:Usuario', property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: pladuch_login_sga
                check_path: pladuch_login_check
                csrf_provider: form.csrf_provider
            logout:
                path: pladuch_logout_sga
                target: pladuch_login_sga

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/gestion, roles: ROLE_ADMIN }
