DROP DATABASE pladuch;
CREATE DATABASE pladuch CHARSET=utf8;

USE pladuch;

CREATE TABLE IF NOT EXISTS idiomas (
	id INT(11) NOT NULL AUTO_INCREMENT,
	iso VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_bin;

CREATE TABLE IF NOT EXISTS muestras (
	id INT(11) NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(255) NOT NULL,
	ruta_foto VARCHAR(255) NULL,
	PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_bin;

CREATE TABLE IF NOT EXISTS materiales (
	id INT(11) NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(255) NOT NULL,
	ruta_foto VARCHAR(255) NULL,
	PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_bin;

CREATE TABLE IF NOT EXISTS catalogo_platos (
	id INT(11) NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(255) NOT NULL,
	ruta_foto VARCHAR(255) NULL,
	PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_bin;

CREATE TABLE IF NOT EXISTS catalogo_platos_traduccion (
	id INT(11) NOT NULL AUTO_INCREMENT,
	catalogoplatos_id INT(11) NOT NULL,
	idioma_id INT(11) NOT NULL,
	descripcion TEXT NULL,
	PRIMARY KEY (id),
	KEY FK_DESCRIPCIONPLATOS_TRADUCCION (catalogoplatos_id),
	CONSTRAINT FK_DESCRIPCIONPLATOS_TRADUCCION FOREIGN KEY (catalogoplatos_id) REFERENCES catalogo_platos(id) ON UPDATE NO ACTION ON DELETE NO ACTION
)ENGINE=INNODB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_bin;

CREATE TABLE IF NOT EXISTS catalogo_materiales (
	id INT(11) NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(255) NOT NULL,
	ruta_foto VARCHAR(255) NULL,
	PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_bin;

CREATE TABLE IF NOT EXISTS catalogo_materiales_traduccion (
	id INT(11) NOT NULL AUTO_INCREMENT,
	catalogomateriales_id INT(11) NOT NULL,
	idioma_id INT(11) NOT NULL,
	descripcion TEXT NULL,
	PRIMARY KEY (id),
	KEY FK_DESCRIPCIONMATERIALES_TRADUCCION (catalogomateriales_id),
	CONSTRAINT FK_DESCRIPCIONMATERIALES_TRADUCCION FOREIGN KEY (catalogomateriales_id) REFERENCES catalogo_materiales(id) ON UPDATE NO ACTION ON DELETE NO ACTION
)ENGINE=INNODB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_bin;

CREATE TABLE IF NOT EXISTS catalogo_trabajos (
	id INT(11) NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(255) NOT NULL,
	ruta_foto VARCHAR(255) NULL,
	PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_bin;

CREATE TABLE IF NOT EXISTS catalogo_trabajos_traduccion (
	id INT(11) NOT NULL AUTO_INCREMENT,
	catalogotrabajos_id INT(11) NOT NULL,
	idioma_id INT(11) NOT NULL,
	descripcion TEXT NULL,
	PRIMARY KEY (id),
	KEY FK_DESCRIPCIONTRABAJOS_TRADUCCION (catalogotrabajos_id),
	CONSTRAINT FK_DESCRIPCIONTRABAJOS_TRADUCCION FOREIGN KEY (catalogotrabajos_id) REFERENCES catalogo_trabajos(id) ON UPDATE NO ACTION ON DELETE NO ACTION
)ENGINE=INNODB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_bin;

CREATE TABLE IF NOT EXISTS rol (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) NOT NULL UNIQUE,
  tipo VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_bin;

CREATE TABLE IF NOT EXISTS usuario (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(1024) NOT NULL,
  salt VARCHAR(1024) NOT NULL,
  email VARCHAR(255) NOT NULL,
  rol_id INT(11) NOT NULL,
  KEY FK_USUARIO_ROL (rol_id),
  PRIMARY KEY (id),
  CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (rol_id) REFERENCES rol(id) ON UPDATE NO ACTION ON DELETE NO ACTION
)ENGINE=INNODB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_bin;
